import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link } from "react-router-dom";
import { FaRegHeart } from "react-icons/fa";
import { HiOutlineShoppingBag } from "react-icons/hi";
import { IoPersonOutline } from "react-icons/io5";
function Navbar() {
    const [menuOpen, setMenuOpen] = useState(false);
    return (_jsxs("nav", { className: "w-full fixed  shadow-md bg-white dark:bg-black z-[100] ", children: [_jsxs("div", { className: "max-w-[1280px] mx-auto flex justify-between items-center py-5 px-6 md:px-16", children: [_jsx(Link, { to: "/", className: "text-2xl font-semibold font-[Playfair Display]  dark:text-white", children: "Aur\u00E9ne" }), _jsxs("div", { className: "hidden md:flex gap-6 font-medium  ", children: [_jsx(Link, { to: "/", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Home" }), _jsx(Link, { to: "/Shop/:category", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Shop" }), _jsx(Link, { to: "/about", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "About" }), _jsx(Link, { to: "/contact", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Contact" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-4 text-xl  dark:text-white", children: [_jsx(Link, { to: "/wishlist", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: _jsx(FaRegHeart, {}) }), _jsx(Link, { to: "/Login", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: _jsx(IoPersonOutline, {}) }), _jsx(Link, { to: "/cart", className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: _jsx(HiOutlineShoppingBag, {}) })] }), _jsx("button", { onClick: () => setMenuOpen(!menuOpen), className: "md:hidden text-3xl text-gray-700  focus:outline-none", children: "\u2630" })] }), menuOpen && (_jsxs("div", { className: "md:hidden flex flex-col items-center gap-4 py-6 bg-white dark:bg-black  dark:text-white shadow-lg", children: [_jsx(Link, { to: "/", onClick: () => setMenuOpen(false), className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Home" }), _jsx(Link, { to: "/Shop/:category", onClick: () => setMenuOpen(false), className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Shop" }), _jsx(Link, { to: "/about", onClick: () => setMenuOpen(false), className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "About" }), _jsx(Link, { to: "/contact", onClick: () => setMenuOpen(false), className: "hover:text-[var(--main)] dark:hover:text-[var(--main)] duration-300", children: "Contact" })] }))] }));
}
export default Navbar;
